### ISSUE TITLE
Rate-limit Exceeded errors

### ISSUE THREAD

**Issue by nileshtrivedi** [suramyatomar/TwitterExtract#2]
While trying to run this script for my own profile `nileshtrivedi`, I got this error:

```
$ python3 ExtractData.py nileshtrivedi
Traceback (most recent call last):
  File "/Users/eshnil/code/TwitterExtract/ExtractData.py", line 75, in <module>
    for value in tweepy.Cursor(api.get_followers, user_id=InputUserID, count=200).items():
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/cursor.py", line 86, in __next__
    return self.next()
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/cursor.py", line 286, in next
    self.current_page = next(self.page_iterator)
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/cursor.py", line 86, in __next__
    return self.next()
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/cursor.py", line 110, in next
    data, cursors = self.method(cursor=self.next_cursor,
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/api.py", line 2161, in get_followers
    return self.request(
  File "/Users/eshnil/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/tweepy/api.py", line 269, in request
    raise TooManyRequests(resp)
tweepy.errors.TooManyRequests: 429 Too Many Requests
88 - Rate limit exceeded
```

**Comment by suramyatomar** [comment]
You get this when you exceed the API rate limit on Twitter.  For lists it is 

List members - 900 queries / 15 mins
Get List members -  900 queries / 15 mins
Get user's List memberships 900 queries/ 15 mins

https://developer.twitter.com/en/docs/twitter-api/rate-limits has more details on the API limits

To resolve wait for about 15 mins and then retry. The other option is to request elevated access which has a higher limit. Last option would be to add code that checks for the limit and then waits but I will not be adding that in the near future as there are other features I would like to implement first.
